
## ------------------------------------------------------
## Mongodb
## ------------------------------------------------------
mongodb:
  enabled: true
  persistence:
    enabled: false
  usePassword: false
  service:
    type: ClusterIP
    port: 27017

## ------------------------------------------------------
## Node-todo
## ------------------------------------------------------
# Default values for node-todo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
serverPort: 8080
image:
  repository: kanolato/node-todo
  branch: master
  version: 0.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: yes
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - node-todo.192.168.99.100.nip.io
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
